// ==UserScript==
// @name         Anubis WebGPU
// @namespace    https://github.com/kasper93/anubis_webgpu
// @version      0.2.0
// @description  Solve Anubis PoW challenges with WebGPU (optimized JS fallback)
// @updateURL    https://github.com/kasper93/anubis_webgpu/raw/refs/heads/master/anubis_webgpu.user.js
// @downloadURL  https://github.com/kasper93/anubis_webgpu/raw/refs/heads/master/anubis_webgpu.user.js
// @match        *://*/*
// @grant        none
// @run-at       document-start
// ==/UserScript==

// Generated by build.ts from src/ - edit those files, not this one.

"use strict";
(() => {
  // src/core.ts
  var K = new Int32Array([
    1116352408,
    1899447441,
    3049323471,
    3921009573,
    961987163,
    1508970993,
    2453635748,
    2870763221,
    3624381080,
    310598401,
    607225278,
    1426881987,
    1925078388,
    2162078206,
    2614888103,
    3248222580,
    3835390401,
    4022224774,
    264347078,
    604807628,
    770255983,
    1249150122,
    1555081692,
    1996064986,
    2554220882,
    2821834349,
    2952996808,
    3210313671,
    3336571891,
    3584528711,
    113926993,
    338241895,
    666307205,
    773529912,
    1294757372,
    1396182291,
    1695183700,
    1986661051,
    2177026350,
    2456956037,
    2730485921,
    2820302411,
    3259730800,
    3345764771,
    3516065817,
    3600352804,
    4094571909,
    275423344,
    430227734,
    506948616,
    659060556,
    883997877,
    958139571,
    1322822218,
    1537002063,
    1747873779,
    1955562222,
    2024104815,
    2227730452,
    2361852424,
    2428436474,
    2756734187,
    3204031479,
    3329325298
  ]);
  var H0 = new Int32Array([
    1779033703,
    3144134277,
    1013904242,
    2773480762,
    1359893119,
    2600822924,
    528734635,
    1541459225
  ]);
  function schedule(w) {
    for (let t = 16; t < 64; t++) {
      const x2 = w[t - 2], x15 = w[t - 15];
      w[t] = ((x2 >>> 17 | x2 << 15) ^ (x2 >>> 19 | x2 << 13) ^ x2 >>> 10) + w[t - 7] + (((x15 >>> 7 | x15 << 25) ^ (x15 >>> 18 | x15 << 14) ^ x15 >>> 3) + w[t - 16]) | 0;
    }
  }
  function rounds(s, w, from, to) {
    let a = s[0], b = s[1], c = s[2], d = s[3], e = s[4], f = s[5], g = s[6], h = s[7];
    for (let t = from; t < to; t++) {
      const t1 = h + ((e >>> 6 | e << 26) ^ (e >>> 11 | e << 21) ^ (e >>> 25 | e << 7)) + (g ^ e & (f ^ g)) + K[t] + w[t] | 0;
      const t2 = ((a >>> 2 | a << 30) ^ (a >>> 13 | a << 19) ^ (a >>> 22 | a << 10)) + (a & b ^ a & c ^ b & c) | 0;
      h = g;
      g = f;
      f = e;
      e = d + t1 | 0;
      d = c;
      c = b;
      b = a;
      a = t1 + t2 | 0;
    }
    s[0] = a;
    s[1] = b;
    s[2] = c;
    s[3] = d;
    s[4] = e;
    s[5] = f;
    s[6] = g;
    s[7] = h;
  }
  var tmpState = new Int32Array(8);
  function compress(s, w) {
    schedule(w);
    tmpState.set(s);
    rounds(tmpState, w, 0, 64);
    for (let i = 0; i < 8; i++) s[i] = s[i] + tmpState[i] | 0;
  }
  function hexOfState(s) {
    let out = "";
    for (let i = 0; i < 8; i++) out += (s[i] >>> 0).toString(16).padStart(8, "0");
    return out;
  }
  function sha256hex(input) {
    const bytes = typeof input === "string" ? new TextEncoder().encode(input) : input;
    const padded = new Uint8Array(bytes.length + 9 + 63 >> 6 << 6);
    padded.set(bytes);
    padded[bytes.length] = 128;
    const bitlen = bytes.length * 8;
    const dv = new DataView(padded.buffer);
    dv.setUint32(padded.length - 8, Math.floor(bitlen / 4294967296));
    dv.setUint32(padded.length - 4, bitlen >>> 0);
    const s = Int32Array.from(H0);
    const w = new Int32Array(64);
    for (let o = 0; o < padded.length; o += 64) {
      for (let i = 0; i < 16; i++) w[i] = dv.getInt32(o + i * 4);
      compress(s, w);
    }
    return hexOfState(s);
  }
  function midstate(bytes) {
    const mid = Int32Array.from(H0);
    const w = new Int32Array(64);
    const nBlocks = Math.floor(bytes.length / 64);
    for (let b = 0; b < nBlocks; b++) {
      for (let i = 0; i < 16; i++) {
        const o = b * 64 + i * 4;
        w[i] = bytes[o] << 24 | bytes[o + 1] << 16 | bytes[o + 2] << 8 | bytes[o + 3];
      }
      compress(mid, w);
    }
    return { mid, rem: bytes.subarray(nBlocks * 64) };
  }
  function masks(difficulty) {
    const m = (bits) => bits === 0 ? 0 : -1 << 32 - bits | 0;
    return [m(Math.min(difficulty, 8) * 4), m(Math.min(Math.max(difficulty - 8, 0), 8) * 4)];
  }
  function nonceString(hi, lo) {
    let out = "1";
    for (let k = 17; k >= 0; k--) {
      let d;
      if (k >= 11) d = hi >>> 3 * k - 32 & 7;
      else if (k === 10) d = (lo >>> 30 | hi << 2) & 7;
      else d = lo >>> 3 * k & 7;
      out += d;
    }
    return out;
  }

  // src/gen/kernels.ts
  function createKernel(env) {
    return function run(n) {
      const W = env.w, T = env.tail, kk = env.K, Pr = env.pre;
      const lo = env.w0, wl = env.wLast, rb = env.rebuildAt, st = env.stride;
      const m0 = env.mask0, m1 = env.mask1, f0 = env.mid0, f1 = env.mid1;
      const add = env.add, rebuild = env.rebuild;
      for (let j = 0; j < n; j++) {
        for (let wi = lo; wi <= wl; wi++)
          W[wi] = T[4 * wi] << 24 | T[4 * wi + 1] << 16 | T[4 * wi + 2] << 8 | T[4 * wi + 3];
        let a = Pr[0] | 0, b = Pr[1] | 0, c = Pr[2] | 0, d = Pr[3] | 0;
        let e = Pr[4] | 0, f = Pr[5] | 0, g = Pr[6] | 0, h = Pr[7] | 0;
        for (let t = lo; t < 16; t++) {
          const t1 = h + ((e >>> 6 | e << 26) ^ (e >>> 11 | e << 21) ^ (e >>> 25 | e << 7)) + (g ^ e & (f ^ g)) + kk[t] + W[t] | 0;
          const t2 = ((a >>> 2 | a << 30) ^ (a >>> 13 | a << 19) ^ (a >>> 22 | a << 10)) + (a & b ^ a & c ^ b & c) | 0;
          h = g;
          g = f;
          f = e;
          e = d + t1 | 0;
          d = c;
          c = b;
          b = a;
          a = t1 + t2 | 0;
        }
        let x2 = 0, x15 = 0;
        let wv0 = W[0] | 0, wv1 = W[1] | 0, wv2 = W[2] | 0, wv3 = W[3] | 0, wv4 = W[4] | 0, wv5 = W[5] | 0, wv6 = W[6] | 0, wv7 = W[7] | 0;
        let wv8 = W[8] | 0, wv9 = W[9] | 0, wv10 = W[10] | 0, wv11 = W[11] | 0, wv12 = W[12] | 0, wv13 = W[13] | 0, wv14 = W[14] | 0, wv15 = W[15] | 0;
        for (let to = 16; to < 64; to += 16) {
          x2 = wv14;
          x15 = wv1;
          wv0 = ((x2 >>> 17 | x2 << 15) ^ (x2 >>> 19 | x2 << 13) ^ x2 >>> 10) + wv9 + (((x15 >>> 7 | x15 << 25) ^ (x15 >>> 18 | x15 << 14) ^ x15 >>> 3) + wv0) | 0;
          h = h + ((e >>> 6 | e << 26) ^ (e >>> 11 | e << 21) ^ (e >>> 25 | e << 7)) + (g ^ e & (f ^ g)) + kk[to + 0] + wv0 | 0;
          d = d + h | 0;
          h = h + ((a >>> 2 | a << 30) ^ (a >>> 13 | a << 19) ^ (a >>> 22 | a << 10)) + (a & b ^ a & c ^ b & c) | 0;
          x2 = wv15;
          x15 = wv2;
          wv1 = ((x2 >>> 17 | x2 << 15) ^ (x2 >>> 19 | x2 << 13) ^ x2 >>> 10) + wv10 + (((x15 >>> 7 | x15 << 25) ^ (x15 >>> 18 | x15 << 14) ^ x15 >>> 3) + wv1) | 0;
          g = g + ((d >>> 6 | d << 26) ^ (d >>> 11 | d << 21) ^ (d >>> 25 | d << 7)) + (f ^ d & (e ^ f)) + kk[to + 1] + wv1 | 0;
          c = c + g | 0;
          g = g + ((h >>> 2 | h << 30) ^ (h >>> 13 | h << 19) ^ (h >>> 22 | h << 10)) + (h & a ^ h & b ^ a & b) | 0;
          x2 = wv0;
          x15 = wv3;
          wv2 = ((x2 >>> 17 | x2 << 15) ^ (x2 >>> 19 | x2 << 13) ^ x2 >>> 10) + wv11 + (((x15 >>> 7 | x15 << 25) ^ (x15 >>> 18 | x15 << 14) ^ x15 >>> 3) + wv2) | 0;
          f = f + ((c >>> 6 | c << 26) ^ (c >>> 11 | c << 21) ^ (c >>> 25 | c << 7)) + (e ^ c & (d ^ e)) + kk[to + 2] + wv2 | 0;
          b = b + f | 0;
          f = f + ((g >>> 2 | g << 30) ^ (g >>> 13 | g << 19) ^ (g >>> 22 | g << 10)) + (g & h ^ g & a ^ h & a) | 0;
          x2 = wv1;
          x15 = wv4;
          wv3 = ((x2 >>> 17 | x2 << 15) ^ (x2 >>> 19 | x2 << 13) ^ x2 >>> 10) + wv12 + (((x15 >>> 7 | x15 << 25) ^ (x15 >>> 18 | x15 << 14) ^ x15 >>> 3) + wv3) | 0;
          e = e + ((b >>> 6 | b << 26) ^ (b >>> 11 | b << 21) ^ (b >>> 25 | b << 7)) + (d ^ b & (c ^ d)) + kk[to + 3] + wv3 | 0;
          a = a + e | 0;
          e = e + ((f >>> 2 | f << 30) ^ (f >>> 13 | f << 19) ^ (f >>> 22 | f << 10)) + (f & g ^ f & h ^ g & h) | 0;
          x2 = wv2;
          x15 = wv5;
          wv4 = ((x2 >>> 17 | x2 << 15) ^ (x2 >>> 19 | x2 << 13) ^ x2 >>> 10) + wv13 + (((x15 >>> 7 | x15 << 25) ^ (x15 >>> 18 | x15 << 14) ^ x15 >>> 3) + wv4) | 0;
          d = d + ((a >>> 6 | a << 26) ^ (a >>> 11 | a << 21) ^ (a >>> 25 | a << 7)) + (c ^ a & (b ^ c)) + kk[to + 4] + wv4 | 0;
          h = h + d | 0;
          d = d + ((e >>> 2 | e << 30) ^ (e >>> 13 | e << 19) ^ (e >>> 22 | e << 10)) + (e & f ^ e & g ^ f & g) | 0;
          x2 = wv3;
          x15 = wv6;
          wv5 = ((x2 >>> 17 | x2 << 15) ^ (x2 >>> 19 | x2 << 13) ^ x2 >>> 10) + wv14 + (((x15 >>> 7 | x15 << 25) ^ (x15 >>> 18 | x15 << 14) ^ x15 >>> 3) + wv5) | 0;
          c = c + ((h >>> 6 | h << 26) ^ (h >>> 11 | h << 21) ^ (h >>> 25 | h << 7)) + (b ^ h & (a ^ b)) + kk[to + 5] + wv5 | 0;
          g = g + c | 0;
          c = c + ((d >>> 2 | d << 30) ^ (d >>> 13 | d << 19) ^ (d >>> 22 | d << 10)) + (d & e ^ d & f ^ e & f) | 0;
          x2 = wv4;
          x15 = wv7;
          wv6 = ((x2 >>> 17 | x2 << 15) ^ (x2 >>> 19 | x2 << 13) ^ x2 >>> 10) + wv15 + (((x15 >>> 7 | x15 << 25) ^ (x15 >>> 18 | x15 << 14) ^ x15 >>> 3) + wv6) | 0;
          b = b + ((g >>> 6 | g << 26) ^ (g >>> 11 | g << 21) ^ (g >>> 25 | g << 7)) + (a ^ g & (h ^ a)) + kk[to + 6] + wv6 | 0;
          f = f + b | 0;
          b = b + ((c >>> 2 | c << 30) ^ (c >>> 13 | c << 19) ^ (c >>> 22 | c << 10)) + (c & d ^ c & e ^ d & e) | 0;
          x2 = wv5;
          x15 = wv8;
          wv7 = ((x2 >>> 17 | x2 << 15) ^ (x2 >>> 19 | x2 << 13) ^ x2 >>> 10) + wv0 + (((x15 >>> 7 | x15 << 25) ^ (x15 >>> 18 | x15 << 14) ^ x15 >>> 3) + wv7) | 0;
          a = a + ((f >>> 6 | f << 26) ^ (f >>> 11 | f << 21) ^ (f >>> 25 | f << 7)) + (h ^ f & (g ^ h)) + kk[to + 7] + wv7 | 0;
          e = e + a | 0;
          a = a + ((b >>> 2 | b << 30) ^ (b >>> 13 | b << 19) ^ (b >>> 22 | b << 10)) + (b & c ^ b & d ^ c & d) | 0;
          x2 = wv6;
          x15 = wv9;
          wv8 = ((x2 >>> 17 | x2 << 15) ^ (x2 >>> 19 | x2 << 13) ^ x2 >>> 10) + wv1 + (((x15 >>> 7 | x15 << 25) ^ (x15 >>> 18 | x15 << 14) ^ x15 >>> 3) + wv8) | 0;
          h = h + ((e >>> 6 | e << 26) ^ (e >>> 11 | e << 21) ^ (e >>> 25 | e << 7)) + (g ^ e & (f ^ g)) + kk[to + 8] + wv8 | 0;
          d = d + h | 0;
          h = h + ((a >>> 2 | a << 30) ^ (a >>> 13 | a << 19) ^ (a >>> 22 | a << 10)) + (a & b ^ a & c ^ b & c) | 0;
          x2 = wv7;
          x15 = wv10;
          wv9 = ((x2 >>> 17 | x2 << 15) ^ (x2 >>> 19 | x2 << 13) ^ x2 >>> 10) + wv2 + (((x15 >>> 7 | x15 << 25) ^ (x15 >>> 18 | x15 << 14) ^ x15 >>> 3) + wv9) | 0;
          g = g + ((d >>> 6 | d << 26) ^ (d >>> 11 | d << 21) ^ (d >>> 25 | d << 7)) + (f ^ d & (e ^ f)) + kk[to + 9] + wv9 | 0;
          c = c + g | 0;
          g = g + ((h >>> 2 | h << 30) ^ (h >>> 13 | h << 19) ^ (h >>> 22 | h << 10)) + (h & a ^ h & b ^ a & b) | 0;
          x2 = wv8;
          x15 = wv11;
          wv10 = ((x2 >>> 17 | x2 << 15) ^ (x2 >>> 19 | x2 << 13) ^ x2 >>> 10) + wv3 + (((x15 >>> 7 | x15 << 25) ^ (x15 >>> 18 | x15 << 14) ^ x15 >>> 3) + wv10) | 0;
          f = f + ((c >>> 6 | c << 26) ^ (c >>> 11 | c << 21) ^ (c >>> 25 | c << 7)) + (e ^ c & (d ^ e)) + kk[to + 10] + wv10 | 0;
          b = b + f | 0;
          f = f + ((g >>> 2 | g << 30) ^ (g >>> 13 | g << 19) ^ (g >>> 22 | g << 10)) + (g & h ^ g & a ^ h & a) | 0;
          x2 = wv9;
          x15 = wv12;
          wv11 = ((x2 >>> 17 | x2 << 15) ^ (x2 >>> 19 | x2 << 13) ^ x2 >>> 10) + wv4 + (((x15 >>> 7 | x15 << 25) ^ (x15 >>> 18 | x15 << 14) ^ x15 >>> 3) + wv11) | 0;
          e = e + ((b >>> 6 | b << 26) ^ (b >>> 11 | b << 21) ^ (b >>> 25 | b << 7)) + (d ^ b & (c ^ d)) + kk[to + 11] + wv11 | 0;
          a = a + e | 0;
          e = e + ((f >>> 2 | f << 30) ^ (f >>> 13 | f << 19) ^ (f >>> 22 | f << 10)) + (f & g ^ f & h ^ g & h) | 0;
          x2 = wv10;
          x15 = wv13;
          wv12 = ((x2 >>> 17 | x2 << 15) ^ (x2 >>> 19 | x2 << 13) ^ x2 >>> 10) + wv5 + (((x15 >>> 7 | x15 << 25) ^ (x15 >>> 18 | x15 << 14) ^ x15 >>> 3) + wv12) | 0;
          d = d + ((a >>> 6 | a << 26) ^ (a >>> 11 | a << 21) ^ (a >>> 25 | a << 7)) + (c ^ a & (b ^ c)) + kk[to + 12] + wv12 | 0;
          h = h + d | 0;
          d = d + ((e >>> 2 | e << 30) ^ (e >>> 13 | e << 19) ^ (e >>> 22 | e << 10)) + (e & f ^ e & g ^ f & g) | 0;
          x2 = wv11;
          x15 = wv14;
          wv13 = ((x2 >>> 17 | x2 << 15) ^ (x2 >>> 19 | x2 << 13) ^ x2 >>> 10) + wv6 + (((x15 >>> 7 | x15 << 25) ^ (x15 >>> 18 | x15 << 14) ^ x15 >>> 3) + wv13) | 0;
          c = c + ((h >>> 6 | h << 26) ^ (h >>> 11 | h << 21) ^ (h >>> 25 | h << 7)) + (b ^ h & (a ^ b)) + kk[to + 13] + wv13 | 0;
          g = g + c | 0;
          c = c + ((d >>> 2 | d << 30) ^ (d >>> 13 | d << 19) ^ (d >>> 22 | d << 10)) + (d & e ^ d & f ^ e & f) | 0;
          x2 = wv12;
          x15 = wv15;
          wv14 = ((x2 >>> 17 | x2 << 15) ^ (x2 >>> 19 | x2 << 13) ^ x2 >>> 10) + wv7 + (((x15 >>> 7 | x15 << 25) ^ (x15 >>> 18 | x15 << 14) ^ x15 >>> 3) + wv14) | 0;
          b = b + ((g >>> 6 | g << 26) ^ (g >>> 11 | g << 21) ^ (g >>> 25 | g << 7)) + (a ^ g & (h ^ a)) + kk[to + 14] + wv14 | 0;
          f = f + b | 0;
          b = b + ((c >>> 2 | c << 30) ^ (c >>> 13 | c << 19) ^ (c >>> 22 | c << 10)) + (c & d ^ c & e ^ d & e) | 0;
          x2 = wv13;
          x15 = wv0;
          wv15 = ((x2 >>> 17 | x2 << 15) ^ (x2 >>> 19 | x2 << 13) ^ x2 >>> 10) + wv8 + (((x15 >>> 7 | x15 << 25) ^ (x15 >>> 18 | x15 << 14) ^ x15 >>> 3) + wv15) | 0;
          a = a + ((f >>> 6 | f << 26) ^ (f >>> 11 | f << 21) ^ (f >>> 25 | f << 7)) + (h ^ f & (g ^ h)) + kk[to + 15] + wv15 | 0;
          e = e + a | 0;
          a = a + ((b >>> 2 | b << 30) ^ (b >>> 13 | b << 19) ^ (b >>> 22 | b << 10)) + (b & c ^ b & d ^ c & d) | 0;
        }
        if ((f0 + a & m0 | f1 + b & m1) === 0) return j + 1;
        if (add(st) < rb) rebuild();
      }
      return 0;
    };
  }

  // src/cpu.ts
  var yieldToEventLoop = (() => {
    const g = globalThis;
    if (g.scheduler?.yield) return () => g.scheduler.yield();
    if (!g.process?.versions?.node && typeof MessageChannel !== "undefined") {
      const ch = new MessageChannel();
      const queue = [];
      ch.port1.onmessage = () => queue.shift()?.();
      return () => new Promise((res) => {
        queue.push(res);
        ch.port2.postMessage(0);
      });
    }
    return () => new Promise((res) => setTimeout(res, 0));
  })();
  async function cpuSolve(data, difficulty, opts = {}) {
    if (difficulty > 16) throw new Error("difficulty > 16 unsupported");
    const bytes = new TextEncoder().encode(data);
    const { mid, rem } = midstate(bytes);
    const r = rem.length;
    if (r + 19 + 1 + 8 > 64) throw new Error("unsupported data length");
    const [mask0, mask1] = masks(difficulty);
    const tail = new Uint8Array(64);
    tail.set(rem, 0);
    tail[r] = 49;
    tail.fill(48, r + 1, r + 19);
    tail[r + 19] = 128;
    const bitlen = (bytes.length + 19) * 8;
    tail[60] = bitlen >>> 24;
    tail[61] = bitlen >>> 16 & 255;
    tail[62] = bitlen >>> 8 & 255;
    tail[63] = bitlen & 255;
    const firstD = r + 1, lastD = r + 18;
    function add(n) {
      let i = lastD, carry = n;
      while (carry > 0) {
        if (i < firstD) throw new Error("nonce space exhausted");
        const v = tail[i] - 48 + carry;
        tail[i] = 48 + (v & 7);
        carry = v >>> 3;
        i--;
      }
      return i + 1;
    }
    if (opts.start) add(opts.start);
    const stride = opts.stride || 1;
    const minDyn = Math.ceil((8 + Math.log2(stride)) / 3);
    const wLast = lastD >> 2;
    let w0 = wLast;
    while (w0 > firstD >> 2 && lastD - Math.max(firstD, w0 << 2) + 1 < minDyn) w0--;
    const rebuildAt = w0 << 2;
    const w = new Int32Array(64);
    const pre = new Int32Array(8);
    function rebuild() {
      for (let i = 0; i < 16; i++)
        w[i] = tail[4 * i] << 24 | tail[4 * i + 1] << 16 | tail[4 * i + 2] << 8 | tail[4 * i + 3];
      pre.set(mid);
      rounds(pre, w, 0, w0);
    }
    rebuild();
    const run = createKernel({
      K,
      w,
      tail,
      pre,
      w0,
      wLast,
      rebuildAt,
      stride,
      mask0,
      mask1,
      mid0: mid[0] | 0,
      mid1: mid[1] | 0,
      add,
      rebuild
    });
    const chunk = opts.chunkSize ?? 1 << 16;
    const maxHashes = opts.maxHashes ?? 2 ** 48;
    const timeLimitMs = opts.timeLimitMs ?? Infinity;
    let hashes = 0;
    const t0 = performance.now();
    for (; ; ) {
      const n = Math.min(chunk, maxHashes - hashes);
      const j = run(n);
      if (j) {
        const s = Int32Array.from(mid);
        compress(s, w);
        let nonce = "";
        for (let i = r; i <= lastD; i++) nonce += String.fromCharCode(tail[i]);
        return {
          found: true,
          nonce,
          hash: hexOfState(s),
          hashes: hashes + j,
          ms: performance.now() - t0,
          backend: "cpu-js"
        };
      }
      hashes += n;
      opts.onProgress?.(hashes);
      const ms = performance.now() - t0;
      if (hashes >= maxHashes || ms > timeLimitMs)
        return { found: false, hashes, ms, backend: "cpu-js" };
      await yieldToEventLoop();
    }
  }

  // src/gpu.ts
  var GPU_STEPS = 256;
  var WG_SIZE = 64;
  function wgslSource() {
    const kList = Array.from(K, (x) => "0x" + (x >>> 0).toString(16) + "u").join(", ");
    return `
struct InParams {
	s0: u32, s1: u32, s2: u32, s3: u32,
	s4: u32, s5: u32, s6: u32, s7: u32,
	base_lo: u32,
	base_hi: u32,
	bitlen: u32,
	mask0: u32,
	mask1: u32,
};

struct OutBuf {
	flag: atomic<u32>,
	nonce_lo: u32,
	nonce_hi: u32,
	hash: array<u32, 8>,
};

@group(0) @binding(0) var<uniform> P: InParams;
@group(0) @binding(1) var<storage, read_write> R: OutBuf;

var<private> KT: array<u32, 64> = array<u32, 64>(${kList});

fn rotr(x: u32, n: u32) -> u32 { return (x >> n) | (x << (32u - n)); }

@compute @workgroup_size(${WG_SIZE})
fn solve(@builtin(global_invocation_id) gid: vec3<u32>, @builtin(num_workgroups) nwg: vec3<u32>) {
	let stride = nwg.x * ${WG_SIZE}u;
	var lo = P.base_lo + gid.x;
	var hi = P.base_hi;
	if (lo < P.base_lo) { hi = hi + 1u; }

	for (var step = 0u; step < ${GPU_STEPS}u; step = step + 1u) {
		// nonce string: '1' then 18 octal digits of (hi:lo), MSB first
		let d0  =  lo         & 7u;
		let d1  = (lo >>  3u) & 7u;
		let d2  = (lo >>  6u) & 7u;
		let d3  = (lo >>  9u) & 7u;
		let d4  = (lo >> 12u) & 7u;
		let d5  = (lo >> 15u) & 7u;
		let d6  = (lo >> 18u) & 7u;
		let d7  = (lo >> 21u) & 7u;
		let d8  = (lo >> 24u) & 7u;
		let d9  = (lo >> 27u) & 7u;
		let d10 = ((lo >> 30u) | (hi << 2u)) & 7u;
		let d11 = (hi >>  1u) & 7u;
		let d12 = (hi >>  4u) & 7u;
		let d13 = (hi >>  7u) & 7u;
		let d14 = (hi >> 10u) & 7u;
		let d15 = (hi >> 13u) & 7u;
		let d16 = (hi >> 16u) & 7u;
		let d17 = (hi >> 19u) & 7u;

		var w: array<u32, 16>;
		w[0] = 0x31303030u | (d17 << 16u) | (d16 << 8u) | d15;
		w[1] = 0x30303030u | (d14 << 24u) | (d13 << 16u) | (d12 << 8u) | d11;
		w[2] = 0x30303030u | (d10 << 24u) | (d9  << 16u) | (d8  << 8u) | d7;
		w[3] = 0x30303030u | (d6  << 24u) | (d5  << 16u) | (d4  << 8u) | d3;
		w[4] = 0x30303080u | (d2  << 24u) | (d1  << 16u) | (d0  << 8u);
		for (var i = 5u; i < 15u; i = i + 1u) { w[i] = 0u; }
		w[15] = P.bitlen;

		var a = P.s0; var b = P.s1; var c = P.s2; var d = P.s3;
		var e = P.s4; var f = P.s5; var g = P.s6; var h = P.s7;

		for (var t = 0u; t < 64u; t = t + 1u) {
			var wv: u32;
			if (t < 16u) {
				wv = w[t];
			} else {
				let x2  = w[(t + 14u) & 15u];
				let x7  = w[(t +  9u) & 15u];
				let x15 = w[(t +  1u) & 15u];
				let x16 = w[ t        & 15u];
				wv = (rotr(x2, 17u) ^ rotr(x2, 19u) ^ (x2 >> 10u)) + x7
				   + (rotr(x15, 7u) ^ rotr(x15, 18u) ^ (x15 >> 3u)) + x16;
				w[t & 15u] = wv;
			}
			let t1 = h + (rotr(e, 6u) ^ rotr(e, 11u) ^ rotr(e, 25u)) + (g ^ (e & (f ^ g))) + KT[t] + wv;
			let t2 = (rotr(a, 2u) ^ rotr(a, 13u) ^ rotr(a, 22u)) + ((a & b) ^ (a & c) ^ (b & c));
			h = g; g = f; f = e; e = d + t1;
			d = c; c = b; b = a; a = t1 + t2;
		}

		let r0 = P.s0 + a;
		let r1 = P.s1 + b;
		if ((r0 & P.mask0) == 0u && (r1 & P.mask1) == 0u) {
			if (atomicExchange(&R.flag, 1u) == 0u) {
				R.nonce_lo = lo;
				R.nonce_hi = hi;
				R.hash[0] = r0;       R.hash[1] = r1;
				R.hash[2] = P.s2 + c; R.hash[3] = P.s3 + d;
				R.hash[4] = P.s4 + e; R.hash[5] = P.s5 + f;
				R.hash[6] = P.s6 + g; R.hash[7] = P.s7 + h;
			}
		}

		let nl = lo + stride;
		if (nl < lo) { hi = hi + 1u; }
		lo = nl;
	}
}
`;
  }
  var GpuSolver = class _GpuSolver {
    device;
    pipeline;
    // Learned dispatch size (in workgroups), carried across solve calls.
    tunedWgs = 4096;
    info;
    dead = false;
    inBuf;
    outBuf;
    staging;
    bindGroup;
    static async create() {
      if (typeof navigator === "undefined" || !navigator.gpu)
        throw new Error("WebGPU not available");
      const adapter = await navigator.gpu.requestAdapter();
      if (!adapter) throw new Error("no WebGPU adapter");
      const device = await adapter.requestDevice();
      const module = device.createShaderModule({ code: wgslSource() });
      const pipeline = await device.createComputePipelineAsync({
        layout: "auto",
        compute: { module, entryPoint: "solve" }
      });
      return new _GpuSolver(device, pipeline, adapter);
    }
    constructor(device, pipeline, adapter) {
      this.device = device;
      this.pipeline = pipeline;
      const inf = adapter.info;
      this.info = inf ? [inf.vendor, inf.architecture || inf.device].filter(Boolean).join(" ") : "unknown adapter";
      device.lost.then(() => {
        this.dead = true;
      });
      const S = GPUBufferUsage;
      this.inBuf = device.createBuffer({ size: 64, usage: S.UNIFORM | S.COPY_DST });
      this.outBuf = device.createBuffer({ size: 48, usage: S.STORAGE | S.COPY_SRC | S.COPY_DST });
      this.staging = device.createBuffer({ size: 48, usage: S.MAP_READ | S.COPY_DST });
      this.bindGroup = device.createBindGroup({
        layout: pipeline.getBindGroupLayout(0),
        entries: [
          { binding: 0, resource: { buffer: this.inBuf } },
          { binding: 1, resource: { buffer: this.outBuf } }
        ]
      });
    }
    // Reads back the result buffer. Firefox invokes WebGPU callbacks from a
    // ~100 ms poll timer (Bugzilla 1870699), but every queue submission also
    // polls; with fastPoll, empty command buffers are submitted while the
    // readback is pending, cutting the wait to a few ms at the cost of some
    // busy-work. Off by default.
    async readResult(fastPoll) {
      const map = this.staging.mapAsync(GPUMapMode.READ);
      if (fastPoll) {
        let pending = true;
        map.then(() => {
          pending = false;
        }, () => {
          pending = false;
        });
        (async () => {
          while (pending && !this.dead) {
            this.device.queue.submit([this.device.createCommandEncoder().finish()]);
            await new Promise((r) => setTimeout(r, 3));
          }
        })();
      }
      await map;
      const res = new Uint32Array(this.staging.getMappedRange().slice(0));
      this.staging.unmap();
      return res;
    }
    async solve(data, difficulty, opts = {}) {
      if (this.dead) throw new Error("GPU device lost");
      if (difficulty > 16) throw new Error("difficulty > 16 unsupported");
      const bytes = new TextEncoder().encode(data);
      if (bytes.length % 64 !== 0)
        throw new Error("GPU path requires data length to be a multiple of 64");
      const { mid } = midstate(bytes);
      const [mask0, mask1] = masks(difficulty);
      const GROW_BELOW_MS = 220, SHRINK_ABOVE_MS = 400, SHRINK_TARGET_MS = 250;
      const HASHES_PER_WG = WG_SIZE * GPU_STEPS;
      const maxWgs = Math.min(65535, this.device.limits.maxComputeWorkgroupsPerDimension);
      let wgs = Math.min(this.tunedWgs, Math.max(
        1,
        Math.ceil(16 ** Math.min(difficulty, 8) / HASHES_PER_WG)
      ));
      const params = new Uint32Array(16);
      for (let i = 0; i < 8; i++) params[i] = mid[i] >>> 0;
      params[10] = (bytes.length + 19) * 8;
      params[11] = mask0 >>> 0;
      params[12] = mask1 >>> 0;
      this.device.queue.writeBuffer(this.outBuf, 0, new Uint32Array(12));
      const maxHashes = opts.maxHashes ?? 2 ** 48;
      const timeLimitMs = opts.timeLimitMs ?? Infinity;
      const t0 = performance.now();
      let base = 0;
      for (; ; ) {
        params[8] = base % 4294967296;
        params[9] = Math.floor(base / 4294967296);
        this.device.queue.writeBuffer(this.inBuf, 0, params);
        const enc = this.device.createCommandEncoder();
        const pass = enc.beginComputePass();
        pass.setPipeline(this.pipeline);
        pass.setBindGroup(0, this.bindGroup);
        pass.dispatchWorkgroups(wgs);
        pass.end();
        enc.copyBufferToBuffer(this.outBuf, 0, this.staging, 0, 48);
        this.device.queue.submit([enc.finish()]);
        const roundT0 = performance.now();
        const res = await this.readResult(opts.fastPoll);
        const roundMs = Math.max(performance.now() - roundT0, 1);
        base += wgs * HASHES_PER_WG;
        if (roundMs < GROW_BELOW_MS) wgs = Math.min(maxWgs, wgs * 2);
        else if (roundMs > SHRINK_ABOVE_MS) wgs = Math.max(1, Math.ceil(wgs / roundMs * SHRINK_TARGET_MS));
        this.tunedWgs = Math.max(this.tunedWgs, wgs);
        if (res[0]) {
          const nonce = nonceString(res[2], res[1]);
          let hash = "";
          for (let i = 3; i < 11; i++) hash += res[i].toString(16).padStart(8, "0");
          if (sha256hex(data + nonce) !== hash)
            throw new Error("GPU result failed verification");
          return { found: true, nonce, hash, hashes: base, ms: performance.now() - t0, backend: "webgpu" };
        }
        opts.onProgress?.(base);
        const ms = performance.now() - t0;
        if (base >= maxHashes || ms > timeLimitMs)
          return { found: false, hashes: base, ms, backend: "webgpu" };
      }
    }
    destroy() {
      this.device.destroy();
      this.dead = true;
    }
  };
  var gpuSolver = null;
  var gpuBusy = Promise.resolve();
  async function gpuInit() {
    if (!gpuSolver || gpuSolver.dead) gpuSolver = await GpuSolver.create();
    return gpuSolver.info;
  }
  function gpuSolve(data, difficulty, opts = {}) {
    const run = gpuBusy.then(async () => {
      try {
        await gpuInit();
        return await gpuSolver.solve(data, difficulty, opts);
      } catch (e) {
        gpuSolver = null;
        throw e;
      }
    });
    gpuBusy = run.catch(() => {
    });
    return run;
  }

  // src/api.ts
  var AnubisPow = {
    K,
    H0,
    schedule,
    rounds,
    compress,
    hexOfState,
    sha256hex,
    midstate,
    masks,
    nonceString,
    cpuSolve,
    gpuSolve,
    gpuInit
  };
  function exposeGlobal() {
    globalThis.AnubisPow = AnubisPow;
  }

  // src/hook.ts
  var LOG_TAG = "[anubis_webgpu]";
  var FAST_POLL = false;
  var CPU_DIFFICULTY_THRESHOLD = 4;
  var MAX_DIFFICULTY = 9;
  var MAX_DATA_LENGTH = 4096;
  var GPU_TIME_LIMIT_MS = 6e4;
  var CPU_TIME_LIMIT_MS = 12e4;
  var ANUBIS_KEYS = /* @__PURE__ */ new Set(["data", "difficulty", "nonce", "threads"]);
  function looksLikeAnubisPow(m) {
    return typeof m === "object" && m !== null && Object.keys(m).every((k) => ANUBIS_KEYS.has(k)) && typeof m.data === "string" && typeof m.difficulty === "number" && typeof m.nonce === "number" && typeof m.threads === "number";
  }
  var challenges = /* @__PURE__ */ new Map();
  function fmtRate(hps) {
    if (hps >= 1e9) return (hps / 1e9).toFixed(2) + "GH/s";
    if (hps >= 1e6) return (hps / 1e6).toFixed(2) + "MH/s";
    return (hps / 1e3).toFixed(0) + "kH/s";
  }
  var rateNode;
  var hud = null;
  function showRate(backend, rate) {
    try {
      if (rateNode === void 0) {
        rateNode = null;
        const status = document.getElementById("status");
        if (status) {
          const walker = document.createTreeWalker(status, NodeFilter.SHOW_TEXT);
          for (let n; n = walker.nextNode(); )
            if (/H\/s\s*$/.test(n.data)) {
              rateNode = n;
              break;
            }
        }
      }
      if (rateNode) {
        rateNode.data = rateNode.data.replace(/\S+$/, fmtRate(rate));
        return;
      }
      if (!hud) {
        hud = document.createElement("div");
        hud.style.cssText = "position:fixed;bottom:8px;right:8px;z-index:2147483647;background:rgba(0,0,0,.8);color:#7c7;font:12px/1.4 ui-monospace,monospace;padding:4px 8px;border-radius:4px;pointer-events:none;white-space:pre";
        (document.body || document.documentElement).appendChild(hud);
      }
      hud.textContent = `${backend}  ${fmtRate(rate)}`;
    } catch {
    }
  }
  function hideRate() {
    hud?.remove();
    hud = null;
  }
  async function solve(message, worker, ch, origPostMessage) {
    const { data, difficulty } = message;
    console.log(LOG_TAG, "intercepted Anubis PoW challenge, difficulty", difficulty);
    const t0 = performance.now();
    const deliver = (payload) => {
      if (typeof worker.onmessage === "function") worker.onmessage(new MessageEvent("message", { data: payload }));
      else worker.dispatchEvent(new MessageEvent("message", { data: payload }));
    };
    let backend = "";
    let lastShown = 0;
    const opts = {
      onProgress: (hashes) => {
        try {
          deliver(hashes);
        } catch (e) {
          console.warn(LOG_TAG, "progress delivery failed:", e);
        }
        const now = performance.now();
        if (now - lastShown > 100) {
          lastShown = now;
          showRate(backend, hashes / (now - t0) * 1e3);
        }
      }
    };
    let res = null;
    if (difficulty <= MAX_DIFFICULTY && data.length <= MAX_DATA_LENGTH) {
      if (difficulty > CPU_DIFFICULTY_THRESHOLD && navigator.gpu) {
        try {
          backend = "webgpu";
          res = await gpuSolve(data, difficulty, { ...opts, timeLimitMs: GPU_TIME_LIMIT_MS, fastPoll: FAST_POLL });
        } catch (e) {
          console.warn(LOG_TAG, "WebGPU failed, falling back to CPU:", e);
          res = null;
        }
      }
      if (!res || !res.found) {
        try {
          backend = "cpu-js";
          res = await cpuSolve(data, difficulty, { ...opts, timeLimitMs: CPU_TIME_LIMIT_MS });
        } catch (e) {
          console.warn(LOG_TAG, "CPU path failed:", e);
          res = null;
        }
      }
    } else {
      console.warn(LOG_TAG, `implausible challenge (difficulty ${difficulty}, ${data.length} bytes), not solving`);
    }
    if (res && res.found) {
      const ms = performance.now() - t0;
      console.log(LOG_TAG, `solved via ${res.backend} in ${ms.toFixed(1)} ms (${res.hashes.toLocaleString()} hashes, ${(res.hashes / ms / 1e3).toFixed(2)} MH/s)`);
      showRate(res.backend, res.hashes / res.ms * 1e3);
      deliver({ hash: res.hash, data, difficulty, nonce: res.nonce });
    } else {
      console.warn(LOG_TAG, "replaying challenge to the page's own workers");
      hideRate();
      for (const s of ch.saved) origPostMessage.apply(s.worker, s.args);
    }
    challenges.delete(data);
  }
  function installHook() {
    const origPostMessage = Worker.prototype.postMessage;
    Worker.prototype.postMessage = function(...args) {
      const message = args[0];
      if (!looksLikeAnubisPow(message)) return origPostMessage.apply(this, args);
      let ch = challenges.get(message.data);
      if (!ch) {
        ch = { saved: [] };
        challenges.set(message.data, ch);
      }
      ch.saved.push({ worker: this, args });
      if (message.nonce === 0) solve(message, this, ch, origPostMessage);
    };
  }

  // src/main.ts
  exposeGlobal();
  installHook();
})();
