#!/usr/bin/env node
// Build: generates src/gen/kernels.ts, bundles dist/anubis_pow.js (dev pages,
// Blob workers) and anubis_webgpu.user.js (the committed userscript).
// Run: node build.ts
import * as esbuild from "esbuild";
import { writeKernelsModule } from "./src/kernelgen.ts";

const VERSION = "0.2.0";

const HEADER = `\
// ==UserScript==
// @name         Anubis WebGPU
// @namespace    https://github.com/kasper93/anubis_webgpu
// @version      ${VERSION}
// @description  Solve Anubis PoW challenges with WebGPU (optimized JS fallback)
// @updateURL    https://github.com/kasper93/anubis_webgpu/raw/refs/heads/master/anubis_webgpu.user.js
// @downloadURL  https://github.com/kasper93/anubis_webgpu/raw/refs/heads/master/anubis_webgpu.user.js
// @match        *://*/*
// @grant        none
// @run-at       document-start
// ==/UserScript==

// Generated by build.ts from src/ - edit those files, not this one.
`;

await writeKernelsModule();

const common: esbuild.BuildOptions = {
	bundle: true,
	format: "iife",
	target: "es2022",
	charset: "utf8",
	legalComments: "none",
};

for (const build of [
	{ entryPoints: ["src/dev.ts"], outfile: "dist/anubis_pow.js" },
	{ entryPoints: ["src/main.ts"], outfile: "anubis_webgpu.user.js", banner: { js: HEADER } },
]) {
	const result = await esbuild.build({ ...common, ...build, metafile: true });
	const [out, meta] = Object.entries(result.metafile!.outputs)[0];
	console.log(`wrote ${out} (${meta.bytes} bytes)`);
}
