#!/usr/bin/env python3
"""Bundle pow-core.js + hook.js into a self-contained userscript."""
import pathlib

ROOT = pathlib.Path(__file__).parent
VERSION = "0.1.0"

HEADER = f"""\
// ==UserScript==
// @name         Anubis WebGPU
// @namespace    https://github.com/kasper93/anubis_webgpu
// @version      {VERSION}
// @description  Solve Anubis PoW challenges with WebGPU (optimized JS fallback)
// @updateURL    https://github.com/kasper93/anubis_webgpu/raw/refs/heads/master/anubis_webgpu.user.js
// @downloadURL  https://github.com/kasper93/anubis_webgpu/raw/refs/heads/master/anubis_webgpu.user.js
// @match        *://*/*
// @grant        none
// @run-at       document-start
// ==/UserScript==

// Generated by make_userscript.py. Edit pow-core.js / hook.js instead.
"""

core = (ROOT / "pow-core.js").read_text(encoding="utf-8")
hook = (ROOT / "hook.js").read_text(encoding="utf-8")

out = HEADER + "(function () {\n'use strict';\n\n" + core + "\n" + hook + "\n})();\n"
(ROOT / "anubis_webgpu.user.js").write_text(out, encoding="utf-8", newline="\n")
print("wrote anubis_webgpu.user.js")
