/*
 * Pure-JS CPU solver.
 *
 * Each attempt re-hashes only the final SHA-256 block (midstate, core.ts).
 * The hot loop:
 *  - memoizes: only the last few nonce digits change per attempt, so the
 *    compression rounds before the first dynamic message word are computed
 *    once per carry event (< once per 512 attempts), not per hash;
 *  - elides the Davies-Meyer feed-forward down to the two output words the
 *    difficulty mask tests; the full hash is redone once on a match;
 *  - runs unrolled rounds with the message schedule fused into 16 locals,
 *    generated by kernelgen.ts.
 */
import { K, rounds, compress, hexOfState, midstate, masks } from "./core.ts";
import { createKernel } from "./gen/kernels.ts";

export interface CpuSolveOptions {
	start?: number;     // first counter value (worker lanes)
	stride?: number;    // counter increment per attempt (worker lanes)
	chunkSize?: number; // attempts between yields/progress callbacks
	maxHashes?: number;
	timeLimitMs?: number;
	onProgress?: (hashes: number) => void;
}

export interface SolveResult {
	found: boolean;
	nonce?: string;
	hash?: string;
	hashes: number;
	ms: number;
	backend: string;
}

// Unclamped yield to the event loop. In browsers setTimeout(0) is clamped to
// ~4 ms once timers nest, which would cost ~25% of a default-sized chunk;
// scheduler.yield and MessageChannel messages are not throttled. Node has no
// such clamp (and its MessagePorts would hold or drop the event loop), so it
// keeps plain setTimeout.
const yieldToEventLoop: () => Promise<void> = (() => {
	const g = globalThis as { scheduler?: { yield?(): Promise<void> }; process?: { versions?: { node?: string } } };
	if (g.scheduler?.yield) return () => g.scheduler!.yield!();
	if (!g.process?.versions?.node && typeof MessageChannel !== "undefined") {
		const ch = new MessageChannel();
		const queue: (() => void)[] = [];
		ch.port1.onmessage = () => queue.shift()?.();
		return () => new Promise<void>(res => { queue.push(res); ch.port2.postMessage(0); });
	}
	return () => new Promise<void>(res => setTimeout(res, 0));
})();

export async function cpuSolve(data: string, difficulty: number, opts: CpuSolveOptions = {}): Promise<SolveResult> {
	if (difficulty > 16) throw new Error("difficulty > 16 unsupported");
	const bytes = new TextEncoder().encode(data);
	const { mid, rem } = midstate(bytes);
	const r = rem.length;
	if (r + 19 + 1 + 8 > 64) throw new Error("unsupported data length");
	const [mask0, mask1] = masks(difficulty);

	// Tail block: remainder | '1' | 18 octal digits | 0x80 | zeros | bitlen
	const tail = new Uint8Array(64);
	tail.set(rem, 0);
	tail[r] = 0x31;
	tail.fill(0x30, r + 1, r + 19);
	tail[r + 19] = 0x80;
	const bitlen = (bytes.length + 19) * 8;
	tail[60] = bitlen >>> 24; tail[61] = (bitlen >>> 16) & 255;
	tail[62] = (bitlen >>> 8) & 255; tail[63] = bitlen & 255;

	const firstD = r + 1, lastD = r + 18;
	function add(n: number): number {
		let i = lastD, carry = n;
		while (carry > 0) {
			if (i < firstD) throw new Error("nonce space exhausted");
			const v = tail[i] - 48 + carry;
			tail[i] = 48 + (v & 7);
			carry = v >>> 3;
			i--;
		}
		return i + 1; // lowest digit index changed
	}
	if (opts.start) add(opts.start);
	const stride = opts.stride || 1;

	// Message words w0..wLast are "dynamic": they hold the counter digits that
	// change while no carry crosses below digit index rebuildAt. Pick w0 so a
	// rebuild happens at most once per >=256 attempts.
	const minDyn = Math.ceil((8 + Math.log2(stride)) / 3);
	const wLast = lastD >> 2;
	let w0 = wLast;
	while (w0 > (firstD >> 2) && lastD - Math.max(firstD, w0 << 2) + 1 < minDyn) w0--;
	const rebuildAt = w0 << 2;

	const w = new Int32Array(64);
	const pre = new Int32Array(8); // a..h after static rounds 0..w0-1

	function rebuild(): void {
		for (let i = 0; i < 16; i++)
			w[i] = (tail[4 * i] << 24) | (tail[4 * i + 1] << 16) | (tail[4 * i + 2] << 8) | tail[4 * i + 3];
		pre.set(mid);
		rounds(pre, w, 0, w0);
	}
	rebuild();

	const run = createKernel({
		K, w, tail, pre, w0, wLast, rebuildAt, stride,
		mask0, mask1, mid0: mid[0] | 0, mid1: mid[1] | 0, add, rebuild,
	});

	const chunk = opts.chunkSize ?? (1 << 16);
	const maxHashes = opts.maxHashes ?? 2 ** 48;
	const timeLimitMs = opts.timeLimitMs ?? Infinity;
	let hashes = 0;
	const t0 = performance.now();

	for (;;) {
		const n = Math.min(chunk, maxHashes - hashes);
		const j = run(n);
		if (j) {
			const s = Int32Array.from(mid);
			compress(s, w);
			let nonce = "";
			for (let i = r; i <= lastD; i++) nonce += String.fromCharCode(tail[i]);
			return {
				found: true, nonce, hash: hexOfState(s),
				hashes: hashes + j, ms: performance.now() - t0, backend: "cpu-js",
			};
		}
		hashes += n;
		opts.onProgress?.(hashes);
		const ms = performance.now() - t0;
		if (hashes >= maxHashes || ms > timeLimitMs)
			return { found: false, hashes, ms, backend: "cpu-js" };
		await yieldToEventLoop();
	}
}
