/*
 * Emits src/gen/kernels.ts, the unrolled SHA-256 hot kernel used by cpu.ts.
 * Run via build.ts (or the tests). The shape - a rolled prologue, then a
 * 3-iteration loop of 16 fused round bodies with the message schedule in 16
 * locals - is the best cross-engine compromise: V8 prefers it fully
 * straight-line (~15% more) but SpiderMonkey regresses badly on that, and the
 * CPU path only matters for difficulty <= 4 one-shot solves anyway.
 */
import { K } from "./core.ts";

// Per-solve state the kernel operates on; see cpu.ts for the semantics.
export interface KernelEnv {
	K: Int32Array;      // round constants
	w: Int32Array;      // 16-word message block (schedule lives in kernel locals)
	tail: Uint8Array;   // final SHA-256 block bytes, incl. the nonce counter digits
	pre: Int32Array;    // a..h after the static rounds 0..w0-1
	w0: number;         // first dynamic message word
	wLast: number;      // last dynamic message word
	rebuildAt: number;  // carry below this digit index invalidates pre
	stride: number;     // counter increment per attempt
	mask0: number;      // difficulty masks for hash words 0 and 1
	mask1: number;
	mid0: number;       // midstate words 0 and 1 (Davies-Meyer feed-forward)
	mid1: number;
	add(n: number): number; // advance counter, returns lowest digit changed
	rebuild(): void;        // recompute pre from the current counter
}

// One chunk of n attempts. Returns the 1-based attempt index of a match (the
// counter then still holds the matching nonce), or 0.
export type Kernel = (n: number) => number;

// Working variables rotate through fixed names: the physical var holding role
// i (a=0..h=7) at round t is phys[(i - t) mod 8]. Each round body updates "h"
// (which becomes next round's "a") and "d" (next round's "e") in place, so no
// shuffling moves are emitted. After round 63 (64 = 0 mod 8) role a is `a` and
// role b is `b` again, whatever the entry round was.
const phys = ["a", "b", "c", "d", "e", "f", "g", "h"];
const P = (i: number, t: number) => phys[(((i - t) % 8) + 8) % 8];

// One fused round body; the K constant comes from `kexpr`.
function round(t: number, wexpr: string, kexpr: string): string {
	const [ra, rb, rc, rd, re, rf, rg, rh] = [0, 1, 2, 3, 4, 5, 6, 7].map(i => P(i, t));
	return `\t\t\t${rh} = (${rh} + (((${re} >>> 6) | (${re} << 26)) ^ ((${re} >>> 11) | (${re} << 21)) ^ ((${re} >>> 25) | (${re} << 7))) + (${rg} ^ (${re} & (${rf} ^ ${rg}))) + ${kexpr} + ${wexpr}) | 0; ` +
		`${rd} = (${rd} + ${rh}) | 0; ` +
		`${rh} = (${rh} + (((${ra} >>> 2) | (${ra} << 30)) ^ ((${ra} >>> 13) | (${ra} << 19)) ^ ((${ra} >>> 22) | (${ra} << 10))) + ((${ra} & ${rb}) ^ (${ra} & ${rc}) ^ (${rb} & ${rc}))) | 0;`;
}

// Message-schedule step kept in 16 ring locals wv0..wv15 (slot = t mod 16).
function expand(t: number): string {
	const s = (k: number) => `wv${k & 15}`;
	return `\t\t\tx2 = ${s(t - 2)}; x15 = ${s(t - 15)}; ` +
		`${s(t)} = (((((x2 >>> 17) | (x2 << 15)) ^ ((x2 >>> 19) | (x2 << 13)) ^ (x2 >>> 10)) + ${s(t - 7)}) + ` +
		`((((x15 >>> 7) | (x15 << 25)) ^ ((x15 >>> 18) | (x15 << 14)) ^ (x15 >>> 3)) + ${s(t - 16)})) | 0;\n`;
}

// Rolled prologue for rounds lo..15, then the ring loop of 16 fused bodies.
function kernelBody(): string {
	let out = `\t\t\tfor (let t = lo; t < 16; t++) {
				const t1 = (h + (((e >>> 6) | (e << 26)) ^ ((e >>> 11) | (e << 21)) ^ ((e >>> 25) | (e << 7))) +
					(g ^ (e & (f ^ g))) + kk[t] + W[t]) | 0;
				const t2 = ((((a >>> 2) | (a << 30)) ^ ((a >>> 13) | (a << 19)) ^ ((a >>> 22) | (a << 10))) +
					((a & b) ^ (a & c) ^ (b & c))) | 0;
				h = g; g = f; f = e; e = (d + t1) | 0;
				d = c; c = b; b = a; a = (t1 + t2) | 0;
			}
			let x2 = 0, x15 = 0;
			let wv0 = W[0] | 0, wv1 = W[1] | 0, wv2 = W[2] | 0, wv3 = W[3] | 0, wv4 = W[4] | 0, wv5 = W[5] | 0, wv6 = W[6] | 0, wv7 = W[7] | 0;
			let wv8 = W[8] | 0, wv9 = W[9] | 0, wv10 = W[10] | 0, wv11 = W[11] | 0, wv12 = W[12] | 0, wv13 = W[13] | 0, wv14 = W[14] | 0, wv15 = W[15] | 0;
			for (let to = 16; to < 64; to += 16) {
`;
	for (let i = 0; i < 16; i++) {
		const t = 16 + i;
		out += expand(t);
		out += round(t, `wv${t & 15}`, `kk[to + ${i}]`) + "\n";
	}
	out += "\t\t\t}\n";
	return out;
}

export function kernelsModuleSource(): string {
	return `// GENERATED by kernelgen.ts (via build.ts or the tests) - do not edit.
import type { KernelEnv, Kernel } from "../kernelgen.ts";

export function createKernel(env: KernelEnv): Kernel {
	return function run(n: number): number {
		const W = env.w, T = env.tail, kk = env.K, Pr = env.pre;
		const lo = env.w0, wl = env.wLast, rb = env.rebuildAt, st = env.stride;
		const m0 = env.mask0, m1 = env.mask1, f0 = env.mid0, f1 = env.mid1;
		const add = env.add, rebuild = env.rebuild;
		for (let j = 0; j < n; j++) {
			for (let wi = lo; wi <= wl; wi++)
				W[wi] = (T[4 * wi] << 24) | (T[4 * wi + 1] << 16) | (T[4 * wi + 2] << 8) | T[4 * wi + 3];
			let a = Pr[0] | 0, b = Pr[1] | 0, c = Pr[2] | 0, d = Pr[3] | 0;
			let e = Pr[4] | 0, f = Pr[5] | 0, g = Pr[6] | 0, h = Pr[7] | 0;
${kernelBody()}
			if ((((f0 + a) & m0) | ((f1 + b) & m1)) === 0) return j + 1;
			if (add(st) < rb) rebuild();
		}
		return 0;
	};
}
`;
}

// Writes src/gen/kernels.ts next to this module. Node-only (build/tests).
export async function writeKernelsModule(): Promise<string> {
	const fs = await import("node:fs");
	const dir = new URL("./gen/", import.meta.url);
	fs.mkdirSync(dir, { recursive: true });
	const path = new URL("./gen/kernels.ts", import.meta.url);
	fs.writeFileSync(path, kernelsModuleSource());
	return path.pathname;
}
