name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - run: npm ci

      - name: Type check
        run: npm run check

      - name: Tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Check commited userscript
        run: git diff --exit-code -- anubis_webgpu.user.js
